/**
 * Disposable / temporary email domain list (550+ domains)
 * Curated from known throwaway email services.
 */
const DISPOSABLE_DOMAINS = new Set([
  // Top-tier disposable services
  "mailinator.com", "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
  "guerrillamail.de", "grr.la", "guerrillamailblock.com", "pokemail.net",
  "sharklasers.com", "spam4.me", "tempmail.com", "temp-mail.org",
  "temp-mail.io", "throwaway.email", "yopmail.com", "yopmail.fr",
  "yopmail.net", "trashmail.com", "trashmail.me", "trashmail.net",
  "trashmail.org", "trashmail.io", "mailnesia.com", "maildrop.cc",
  "dispostable.com", "mailcatch.com", "fakeinbox.com", "tempail.com",
  "tempr.email", "discard.email", "discardmail.com", "discardmail.de",

  // 10minutemail variants
  "10minutemail.com", "10minutemail.net", "10minutemail.org",
  "10minutemail.co.za", "10minutemail.de", "10minutemail.be",
  "minutemail.com", "tempinbox.com",

  // Guerrilla derivatives
  "guerrillamail.biz", "guerrillamail.info",

  // Mailinator variants
  "mailinator.net", "mailinator.org", "mailinator2.com",
  "mailinater.com", "mailinator.us",

  // Common disposable domains
  "adf.ly", "agedmail.com", "anonymbox.com", "antichef.com",
  "antichef.net", "antireg.com", "antispam.de", "antispam24.de",
  "binkmail.com", "bio-muesli.net", "bobmail.info", "bodhi.lawlita.com",
  "bofthew.com", "bootybay.de", "boun.cr", "bouncr.com",
  "breakthru.com", "brefmail.com", "broadbandninja.com", "bsnow.net",
  "bugmenot.com", "bumpymail.com", "bund.us", "bundes-ede.de",
  "burnthespam.info", "buymoreplays.com", "byom.de",

  // C
  "cachecam.com", "card.zp.ua", "casualdx.com", "cek.pm",
  "cellurl.com", "center-mail.de", "chacuo.net", "chammy.info",
  "cheatmail.de", "childsavetrust.org", "choicemail1.com",
  "clixser.com", "cmail.club", "cmail.com", "cmail.net",
  "cmail.org", "coldemail.info", "consumerriot.com", "cool.fr.nf",
  "correo.blogos.net", "cosmorph.com", "courriel.fr.nf",
  "courrieltemporaire.com", "crapmail.org", "crazymailing.com",
  "cubiclink.com", "curryworld.de", "cust.in",

  // D
  "dacoolest.com", "dandikmail.com", "dayrep.com", "dbunker.com",
  "dcemail.com", "deadaddress.com", "deadfake.cf", "deadfake.ga",
  "deadfake.ml", "deadfake.tk", "deadspam.com", "deagot.com",
  "dealja.com", "despam.it", "despammed.com", "devnullmail.com",
  "dfgh.net", "digitalsanctuary.com", "dingbone.com",
  "disbox.net", "disbox.org", "disposableaddress.com",
  "disposableemailaddresses.emailmiser.com", "disposableinbox.com",
  "dispose.it", "dm.w3internet.co.uk", "dodgeit.com",
  "dodgit.com", "dodgit.org", "doiea.com", "domozmail.com",
  "donemail.ru", "dontreg.com", "dontsendmespam.de",
  "drdrb.com", "drdrb.net", "droplar.com", "dropmail.me",
  "duam.net", "dudmail.com", "dump-email.info", "dumpandjunk.com",
  "dumpmail.de", "dumpyemail.com", "duskmail.com",

  // E
  "e4ward.com", "easytrashmail.com", "ee1.pl", "ee2.pl",
  "eelmail.com", "einmalmail.de", "einrot.com", "einrot.de",
  "eintagsmail.de", "email-fake.cf", "email-fake.com",
  "email-fake.ga", "email-fake.gq", "email-fake.ml",
  "email-fake.tk", "email60.com", "emailage.cf", "emailage.ga",
  "emailage.gq", "emailage.ml", "emailage.tk", "emaildienst.de",
  "emailgo.de", "emailias.com", "emailigo.de", "emailinfive.com",
  "emaillime.com", "emailmiser.com", "emailproxsy.com",
  "emails.ga", "emailsensei.com", "emailspam.cf", "emailspam.ga",
  "emailspam.gq", "emailspam.ml", "emailspam.tk", "emailtemporanea.com",
  "emailtemporanea.net", "emailtemporar.ro", "emailtemporario.com.br",
  "emailthe.net", "emailtmp.com", "emailto.de", "emailwarden.com",
  "emailx.at.hm", "emailxfer.com", "emeil.in", "emeil.ir",
  "emz.net", "enterto.com", "ephemail.net", "ero-tube.org",
  "etranquil.com", "etranquil.net", "etranquil.org",
  "evopo.com", "explodemail.com", "express.net.ua",

  // F
  "fakeinbox.cf", "fakeinbox.ga", "fakeinbox.gq", "fakeinbox.ml",
  "fakeinbox.tk", "fakemail.fr", "fakemailgenerator.com",
  "fakemailz.com", "fammix.com", "fansworldwide.de",
  "fantasymail.de", "fastacura.com", "fastchevy.com",
  "fastchrysler.com", "fastkawasaki.com", "fastmazda.com",
  "fastmitsubishi.com", "fastnissan.com", "fastsubaru.com",
  "fastsuzuki.com", "fasttoyota.com", "fastyamaha.com",
  "filzmail.com", "fixmail.tk", "fizmail.com",
  "fleckens.hu", "flemail.ru", "flyspam.com",
  "footard.com", "forgetmail.com", "fr33mail.info",
  "frapmail.com", "free-email.cf", "free-email.ga",
  "freundin.ru", "friendlymail.co.uk", "front14.org",
  "fuckingduh.com", "fudgerub.com", "fux0ringduh.com",

  // G
  "garliclife.com", "gehensiull.com", "get1mail.com",
  "get2mail.fr", "getairmail.cf", "getairmail.com",
  "getairmail.ga", "getairmail.gq", "getairmail.ml",
  "getairmail.tk", "getmails.eu", "getonemail.com",
  "getonemail.net", "ghosttexter.de", "gibit.us",
  "gishpuppy.com", "gmal.com", "gmial.com",
  "goemailgo.com", "gorillaswithdirtyarmpits.com",
  "gotmail.com", "gotmail.net", "gotmail.org",
  "gowikibooks.com", "gowikicampus.com", "gowikicars.com",
  "gowikifilms.com", "gowikigames.com", "gowikimusic.com",
  "gowikinetwork.com", "gowikitravel.com", "gowikitv.com",
  "grandmamail.com", "grandmasmail.com", "great-host.in",
  "greensloth.com", "grr.la", "gsrv.co.uk",
  "guerrillamail.biz", "guerrillamail.info",

  // H
  "h8s.org", "hacccc.com", "haltospam.com", "harakirimail.com",
  "hartbot.de", "hatespam.org", "hellodream.mobi",
  "herp.in", "hidemail.de", "hidzz.com", "hmamail.com",
  "hopemail.biz", "hot-mail.cf", "hot-mail.ga",
  "hot-mail.gq", "hot-mail.ml", "hot-mail.tk",
  "hotpop.com", "hulapla.de", "hushmail.cf",

  // I
  "ieatspam.eu", "ieatspam.info", "ieh-mail.de",
  "ihateyoualot.info", "iheartspam.org", "ikbenull.com",
  "imails.info", "inbax.tk", "inbox.si", "inboxalias.com",
  "inboxclean.com", "inboxclean.org", "inboxproxy.com",
  "incognitomail.com", "incognitomail.net", "incognitomail.org",
  "insorg-mail.info", "instantemailaddress.com",
  "ipoo.org", "irish2me.com", "iwi.net",

  // J-K
  "jetable.com", "jetable.fr.nf", "jetable.net",
  "jetable.org", "jnxjn.com", "jourrapide.com",
  "jsrsolutions.com", "junk1.com", "junkmail.com",
  "junkmail.ga", "junkmail.gq", "kasmail.com",
  "kaspop.com", "keepmymail.com", "killmail.com",
  "killmail.net", "kimsdisk.com", "kingsq.ga",
  "kitnastar.com", "klassmaster.com", "klassmaster.net",
  "klzlk.com", "koszmail.pl", "kurzepost.de",

  // L
  "lawlita.com", "letthemeatspam.com", "lhsdv.com",
  "lifebyfood.com", "link2mail.net", "litedrop.com",
  "lkgn.se", "llogin.ru", "loadby.us",
  "login-email.cf", "login-email.ga", "login-email.ml",
  "login-email.tk", "logular.com", "lol.ovpn.to",
  "lolfreak.net", "lookugly.com", "lopl.co.cc",
  "lortemail.dk", "lovemeleaveme.com", "lr78.com",
  "lroid.com", "lukop.dk",

  // M
  "m21.cc", "mail-filter.com", "mail-temporaire.fr",
  "mail.by", "mail.mezimages.net", "mail.zp.ua",
  "mail114.net", "mail1a.de", "mail21.cc",
  "mail2rss.org", "mail333.com", "mail4trash.com",
  "mailbidon.com", "mailblocks.com", "mailblog.biz",
  "mailbucket.org", "mailcat.biz", "mailcz.info",
  "mailde.de", "mailde.info", "maildx.com",
  "maileater.com", "mailed.ro", "mailexpire.com",
  "mailfa.tk", "mailforspam.com", "mailfree.ga",
  "mailfree.gq", "mailfree.ml", "mailfreeonline.com",
  "mailfs.com", "mailguard.me", "mailhazard.com",
  "mailhazard.us", "mailhz.me", "mailimate.com",
  "mailin8r.com", "mailinater.com", "mailincubator.com",
  "mailismagic.com", "mailjunk.cf", "mailjunk.ga",
  "mailjunk.gq", "mailjunk.ml", "mailjunk.tk",
  "mailmate.com", "mailme.gq", "mailme.ir",
  "mailme.lv", "mailme24.com", "mailmetrash.com",
  "mailmoat.com", "mailms.com", "mailnator.com",
  "mailnull.com", "mailorg.org", "mailpick.biz",
  "mailproxsy.com", "mailquack.com", "mailrock.biz",
  "mailscrap.com", "mailshell.com", "mailsiphon.com",
  "mailslapping.com", "mailslite.com", "mailtemp.info",
  "mailtome.de", "mailtothis.com", "mailtrash.net",
  "mailtv.net", "mailtv.tv", "mailzilla.com",
  "mailzilla.org", "mailzilla.orgmbx.cc",
  "makemetheking.com", "manifestgenerator.com",
  "manybrain.com", "mbx.cc", "mega.zik.dj",
  "meinspamschutz.de", "meltmail.com", "messagebeamer.de",
  "mezimages.net", "mfsa.ru", "mierdamail.com",
  "migmail.pl", "migumail.com", "minimail.eu",
  "mintemail.com", "misterpinball.de", "mjukgansen.com",
  "moakt.com", "mobi.web.id", "mobileninja.co.uk",
  "mohmal.com", "moncourrier.fr.nf", "monemail.fr.nf",
  "monmail.fr.nf", "monumentmail.com", "msa.minsmail.com",
  "mt2015.com", "mx0.wwwnew.eu", "my10minutemail.com",
  "myalias.pw", "mycard.net.ua", "mycleaninbox.net",
  "myemailboxy.com", "mymail-in.net", "mymailoasis.com",
  "mynetstore.de", "mypacks.net", "mypartyclip.de",
  "myphantom.com", "mysamp.de", "myspaceinc.com",
  "myspaceinc.net", "myspaceinc.org", "myspacepimpedup.com",
  "mytemp.email", "mytempmail.com", "mytrashmail.com",
  "myzx.com",

  // N
  "nabala.com", "nada.email", "nada.ltd", "nagi.be",
  "nanonym.ch", "naskotk.cf", "naskotk.ga",
  "naskotk.gq", "naskotk.ml", "naskotk.tk",
  "nedprogo.com", "nervmich.net", "nervtansen.de",
  "netmails.com", "netmails.net", "neverbox.com",
  "nice-4u.com", "nincsmail.hu", "nmail.cf",
  "nnh.com", "no-spam.ws", "noblepioneer.com",
  "nobulk.com", "noclickemail.com", "nogmailspam.info",
  "nomail.ch", "nomail.xl.cx", "nomail2me.com",
  "nomorespamemails.com", "nonspam.eu", "nonspammer.de",
  "noref.in", "nospam.ze.tc", "nospam4.us",
  "nospamfor.us", "nospammail.net", "nospamthanks.info",
  "nothingtoseehere.ca", "notmailinator.com",
  "notsomuch.com", "nowhere.org", "nowmymail.com",
  "nurfuerspam.de", "nus.edu.sg",

  // O
  "objectmail.com", "obobbo.com", "odaymail.com",
  "odnorazovoe.ru", "one-time.email", "oneoffemail.com",
  "oneoffmail.com", "onewaymail.com", "oopi.org",
  "opayq.com", "ordinaryamerican.net", "otherinbox.com",
  "ourklips.com", "outlawspam.com", "ovpn.to",
  "owlpic.com",

  // P
  "pancakemail.com", "paplease.com", "pcusers.otherinbox.com",
  "pepbot.com", "pfui.ru", "pimpedupmyspace.com",
  "pjjkp.com", "plexolan.de", "poczta.onet.pl",
  "politikerclub.de", "poofy.org", "pookmail.com",
  "privacy.net", "privy-mail.com", "privymail.de",
  "promailt.com", "proprietativalam.ro", "propscore.com",
  "protectmail.org", "proxymail.eu", "prtnx.com",
  "punkass.com", "putthisinyouremail.com", "pwrby.com",

  // Q-R
  "qisdo.com", "qisoa.com", "qq.com",
  "quickinbox.com", "quickmail.nl", "rainmail.biz",
  "rcpt.at", "reallymymail.com", "realtyalerts.ca",
  "recode.me", "recursor.net", "recyclemail.dk",
  "regbypass.com", "regbypass.comsafe-mail.net",
  "rejectmail.com", "reliable-mail.com", "remail.cf",
  "remail.ga", "rhyta.com", "rklips.com",
  "rmqkr.net", "royal.net", "rppkn.com",
  "rtrtr.com", "rubyridge.com", "rudymail.ml",
  "ruffrey.com", "ruru.be", "rustydoor.com",
  "rvb.ro",

  // S
  "s0ny.net", "safe-mail.net", "safersignup.de",
  "safetymail.info", "safetypost.de", "sandelf.de",
  "saynotospams.com", "scatmail.com", "schafmail.de",
  "schrott-email.de", "secretemail.de", "secure-mail.biz",
  "selfdestructingmail.com", "sendspamhere.com",
  "senseless-entertainment.com", "services391.com",
  "sharedmailbox.org", "sharklasers.com", "shieldedmail.com",
  "shieldemail.com", "shiftmail.com", "shitmail.me",
  "shitmail.org", "shitware.nl", "shmeriously.com",
  "shortmail.net", "showslow.de", "sibmail.com",
  "sinnlos-mail.de", "siteposter.net", "skeefmail.com",
  "slaskpost.se", "slipry.net", "slopsbox.com",
  "slowslow.de", "slutty.horse", "smashmail.de",
  "smellfear.com", "snakemail.com", "sneakemail.com",
  "sneakymail.de", "snkmail.com", "sofimail.com",
  "sofort-mail.de", "softpls.asia", "sogetthis.com",
  "soisz.com", "solvemail.info", "soodomail.com",
  "soodonims.com", "spam.la", "spam.su",
  "spam4.me", "spamavert.com", "spambob.com",
  "spambob.net", "spambob.org", "spambog.com",
  "spambog.de", "spambog.ru", "spambox.info",
  "spambox.irishspringrealty.com", "spambox.us",
  "spamcannon.com", "spamcannon.net", "spamcero.com",
  "spamcon.org", "spamcorptastic.com", "spamcowboy.com",
  "spamcowboy.net", "spamcowboy.org", "spamday.com",
  "spamex.com", "spamfighter.cf", "spamfighter.ga",
  "spamfighter.gq", "spamfighter.ml", "spamfighter.tk",
  "spamfree24.com", "spamfree24.de", "spamfree24.eu",
  "spamfree24.info", "spamfree24.net", "spamfree24.org",
  "spamgoes.in", "spamherelots.com", "spamhereplease.com",
  "spamhole.com", "spamify.com", "spaminator.de",
  "spamkill.info", "spaml.com", "spaml.de",
  "spammotel.com", "spamobox.com", "spamoff.de",
  "spamslicer.com", "spamspot.com", "spamstack.net",
  "spamthis.co.uk", "spamtrap.ro", "spamtrail.com",
  "spamwc.de", "speedgaus.net", "spikio.com",
  "spoofmail.de", "squizzy.de", "sry.li",
  "ssoia.com", "startkeys.com", "stexsy.com",
  "stinkefinger.net", "stop-my-spam.cf", "stop-my-spam.com",
  "stop-my-spam.ga", "stop-my-spam.ml", "stop-my-spam.tk",
  "streetwisemail.com", "stuffmail.de", "supergreatmail.com",
  "supermailer.jp", "superrito.com", "superstachel.de",
  "suremail.info", "svk.jp", "sweetxxx.de",
  "sylvannet.com",

  // T
  "tafmail.com", "tafoi.gr", "tagyoureit.com",
  "talkinator.com", "tapchicuoihoi.com", "teewars.org",
  "teleworm.com", "teleworm.us", "temp.emeraldcraft.com",
  "temp.headstrong.de", "tempalias.com", "tempe4mail.com",
  "tempemail.biz", "tempemail.co.za", "tempemail.com",
  "tempemail.net", "tempinbox.co.uk", "tempinbox.com",
  "tempmail.eu", "tempmail.it", "tempmail2.com",
  "tempmaildemo.com", "tempmailer.com", "tempmailer.de",
  "tempomail.fr", "temporarily.de", "temporarioemail.com.br",
  "temporaryemail.net", "temporaryemail.us",
  "temporaryforwarding.com", "temporaryinbox.com",
  "temporarymailaddress.com", "tempthe.net",
  "thanksnospam.info", "thankyou2010.com",
  "thc.st", "thecriminals.com", "thejoker5.com",
  "thisisnotmyrealemail.com", "thismail.net",
  "thismail.ru", "throam.com", "throwam.com",
  "throwawayemailaddress.com", "tilien.com",
  "tittbit.in", "tizi.com", "tmailinator.com",
  "toiea.com", "toomail.biz", "topranklist.de",
  "tradermail.info", "trash-amil.com", "trash-mail.at",
  "trash-mail.cf", "trash-mail.com", "trash-mail.de",
  "trash-mail.ga", "trash-mail.gq", "trash-mail.ml",
  "trash-mail.tk", "trash2009.com", "trash2010.com",
  "trash2011.com", "trashdevil.com", "trashdevil.de",
  "trashemails.de", "trashinbox.com", "trashmail.at",
  "trashmail.de", "trashmail.ws", "trashmailer.com",
  "trashymail.com", "trashymail.net", "trbvm.com",
  "trbvn.com", "trialmail.de", "trickmail.net",
  "trillianpro.com", "tryalert.com", "turual.com",
  "twinmail.de", "twoweirdtricks.com", "tyldd.com",

  // U-V
  "uggsrock.com", "umail.net", "unmail.ru",
  "upliftnow.com", "uplipht.com", "uroid.com",
  "valemail.net", "venompen.com", "veryreallyfakeemails.com",
  "viditag.com", "viewcastmedia.com", "viewcastmedia.net",
  "viewcastmedia.org", "vomoto.com", "vpn.st",
  "vsimcard.com",

  // W
  "walkmail.net", "walkmail.ru", "webemail.me",
  "webm4il.info", "webuser.in", "wee.my",
  "weg-werf-email.de", "wegwerf-email-addressen.de",
  "wegwerf-emails.de", "wegwerfadresse.de",
  "wegwerfemail.com", "wegwerfemail.de", "wegwerfmail.de",
  "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org",
  "wetrainbayou.com", "wh4f.org", "whatiaas.com",
  "whatpaas.com", "whatsaas.com", "whopy.com",
  "whtjddn.33mail.com", "wickmail.net", "wilemail.com",
  "willhackforfood.biz", "willselfdestruct.com",
  "winemaven.info", "wronghead.com", "wuzup.net",
  "wuzupmail.net",

  // X-Y-Z
  "xagloo.com", "xemaps.com", "xents.com",
  "xjoi.com", "xmaily.com", "xoxy.net",
  "xyzfree.net", "yapped.net", "yeah.net",
  "yep.it", "yogamaven.com", "yomail.info",
  "yopmail.com", "yopmail.fr", "yopmail.gq",
  "yopmail.net", "you-spam.com", "ypmail.webarnak.fr.eu.org",
  "yuurok.com", "zehnminuten.de", "zehnminutenmail.de",
  "zippymail.info", "zoaxe.com", "zoemail.com",
  "zoemail.net", "zoemail.org", "zomg.info",
  "zxcv.com", "zxcvbnm.com", "zzrgg.com"
]);

module.exports = { DISPOSABLE_DOMAINS };
